server:
  port: 8091
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:6666/authDb'
    username: postgres
    password: root
    oracleucp:
      s-q-l-for-validate-connection:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

