server:
  port: 3333
spring:
  main:
    web-application-type: reactive
  zipkin:
    enabled: true
    base-url: http://34.118.1.180:9411/
    service-name: service-api-gateway
  application:
    name: service-api-gateway
  cloud:
    gateway:
      routes:
        - id: service-auth
          uri: http://192.168.1.107:8091
          predicates:
                 - Path=/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback
        - id: service-user
          uri: http://192.168.1.107:8090
          predicates:
              - Path=/v1/profile/**
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback