server:
  port: ${SERVICE_GATEWAY_PORT}
spring:
  main:
    web-application-type: reactive
  zipkin:
    enabled: true
    base-url: ${SOCIALMEDIA_ZIPKKIN_BASE_URL}
    service-name: ${SERVICE_GATEWAY_NAME}
  application:
    name: service-api-gateway
  cloud:
    gateway:
      routes:
        - id: service-auth
          uri: http://192.168.1.107:8091
          predicates:
                 - Path=/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback
        - id: service-user
          uri: http://192.168.1.107:8090
          predicates:
              - Path=/v1/profile/**
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback
        - id: service-user-follow
          uri:
            http://192.168.1.107:8090
          predicates:
              - Path=/v1/follow/**
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback
        - id: service-user-post
          uri:
            http://192.168.1.107:8090
          predicates:
              - Path=/v1/post/**
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback
        - id: uservice-user-user
          uri:
            http://192.168.1.107:8090
          predicates:
              - Path=/v1/user/**
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback
        - id: uservice-web
          uri:
            http://192.168.1.107:80
          predicates:
              - Path=/web/**
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback
            - RewritePath=/web/?(?<segment>.*), /$\{segment}