server:
  port:  ${SERVICE_CONFIG_PORT}

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services
  security:
    user:
      name: admin
      password: ${DEVELOPER_KEY}
  zipkin:
    enabled: true
    base-url: ${SOCIALMEDIA_ZIPKKIN_BASE_URL}
    service-name: ${SERVICE_CONFIG_NAME}
logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  file:
    name: "log-${SERVICE_CONFIG_NAME}.log"