server:
  port: ${SERVICE_WEB_PORT}

spring:
  zipkin:
    enabled: true
    base-url: ${SOCIALMEDIA_ZIPKKIN_BASE_URL}
    service-name: ${SERVICE_WEB_NAME}
logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  file:
    name: "log-${SERVICE_WEB_NAME}.log"

s3:
  accesskey: ${AWS_ACCESS_KEY}
  secretkey: ${AWS_SECRET_KEY}
