server:
  port: 7777

spring:
  rabbitmq:
    host: 34.118.55.146
    port: 5672
    username: service-elasticsearch
    password: ${DEVELOPER_KEY}
  elasticsearch:
    uris: http://34.118.33.14:9200
  zipkin:
    enabled: true
    base-url: http://34.118.1.180:9411/
    service-name: ervice-elasticsearch
logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  file:
    name: log-service-elasticsearch.log
