server:
  port: ${SERVICE_AUTH_PORT}

spring:
  redis:
    host: ${SOCIALMEDIA_REDIS_BASE_URL}
    port: ${SOCIALMEDIA_REDIS_BASE_PORT}

  rabbitmq:
    host: ${SOCIALMEDIA_RABBITMQ_URL}
    port: ${SOCIALMEDIA_RABBITMQ_PORT}
    username: ${SERVICE_AUTH_NAME}
    password: ${SOCIALMEDIA_RABBITMQ_PASSWORD}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SOCIALMEDIA_POSTGRESQL_BASE_URL}
    username: ${SOCIALMEDIA_POSTGRESQL_USERNAME}
    password:  ${SOCIALMEDIA_POSTGRESQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format-sql: true
  zipkin:
    enabled: true
    base-url: ${SOCIALMEDIA_ZIPKKIN_BASE_URL}
    service-name: ${SERVICE_AUTH_NAME}
logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  file:
    name: "log-${SERVICE_AUTH_NAME}.log"
myapplication:
  userservice: ${SOCIALMEDIA_SERVICE_USER_HOST}