server:
  port: 8091

spring:
  rabbitmq:
    host: 34.118.55.146
    port: 5672
    username: serviceauth
    password: ${DEVELOPER_KEY}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://34.118.40.176:5432/authDb'
    username: postgres
    password: ${DEVELOPER_KEY}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format-sql: true
  zipkin:
    enabled: true
    base-url: http://34.118.1.180:9411/
    service-name: service-auth
logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  file:
    name: log-service-auth.log
myapplication:
  userservice: 192.168.1.107:8090