server:
  port: ${SERVICE_ELASTIC_SEARCH_PORT}

spring:
  rabbitmq:
    host: ${SOCIALMEDIA_RABBITMQ_URL}
    port: ${SOCIALMEDIA_RABBITMQ_PORT}
    username: ${SERVICE_ELASTIC_SEARCH_NAME}
    password: ${SOCIALMEDIA_RABBITMQ_PASSWORD}
  elasticsearch:
    uris: ${SOCIALMEDIA_ELASTICSEARC_BASE_URL}
  zipkin:
    enabled: true
    base-url: ${SOCIALMEDIA_ZIPKKIN_BASE_URL}
    service-name: ${SERVICE_ELASTIC_SEARCH_NAME}
logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  file:
    name: "log-${SERVICE_ELASTIC_SEARCH_NAME}.log"
