spring:
  application:
    name: service-elasticsearch
  cloud:
    config:
      username: ${SOCIALMEDIA_CONFIG_USERNAME}
      password: ${SOCIALMEDIA_CONFIG_PASSWORD}
      uri: ${SOCIALMEDIA_CONFIG_BASE_URL}
  config:
    import: "configserver:"


